Initializing North Robot...
Physical initialization of North Robot...
Moving robot to home position
   vial_index           vial_name         location  location_index  vial_volume  capped cap_type vial_type    home_location  home_location_index
0           0  measurement_vial_0    main_8mL_rack               0          0.0    True     open      8_mL    main_8mL_rack                    0
1           1  measurement_vial_1    main_8mL_rack               1          0.0    True     open      8_mL    main_8mL_rack                    1
2           2  measurement_vial_2    main_8mL_rack               2          0.0    True     open      8_mL    main_8mL_rack                    2
3           3       liquid_source  large_vial_rack               2         20.0    True     open     20_mL  large_vial_rack                    2
Visualizing...
Only hit enter if the status of the vials (including open/close) is correct, otherwise hit ctrl-cMoving vial measurement_vial_0 to clamp: 0
Grabbing vial
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Getting pipet number: 0 from rack 1
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.017835423164069653 mL then waiting 0 s
Aspirating 0.01 mL then waiting 2.4461414013057947 s
Aspirating 0.06696860147640109 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.09480402464047073 mL then waiting 19.878292763605714 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.017835423164069653 mL then waiting 0 s
Aspirating 0.01 mL then waiting 2.4461414013057947 s
Aspirating 0.06696860147640109 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.09480402464047073 mL then waiting 19.878292763605714 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.017835423164069653 mL then waiting 0 s
Aspirating 0.01 mL then waiting 2.4461414013057947 s
Aspirating 0.06696860147640109 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.09480402464047073 mL then waiting 19.878292763605714 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.03968064719811082 mL then waiting 0 s
Aspirating 0.01 mL then waiting 25.44153342023492 s
Aspirating 0.016287294682115316 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.06596794188022613 mL then waiting 12.852779868990183 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.03968064719811082 mL then waiting 0 s
Aspirating 0.01 mL then waiting 25.44153342023492 s
Aspirating 0.016287294682115316 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.06596794188022613 mL then waiting 12.852779868990183 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.03968064719811082 mL then waiting 0 s
Aspirating 0.01 mL then waiting 25.44153342023492 s
Aspirating 0.016287294682115316 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.06596794188022613 mL then waiting 12.852779868990183 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.054781165439635515 mL then waiting 0 s
Aspirating 0.01 mL then waiting 13.368342155590653 s
Aspirating 0.08675120174884797 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.1515323671884835 mL then waiting 27.554954756051302 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.054781165439635515 mL then waiting 0 s
Aspirating 0.01 mL then waiting 13.368342155590653 s
Aspirating 0.08675120174884797 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.1515323671884835 mL then waiting 27.554954756051302 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.054781165439635515 mL then waiting 0 s
Aspirating 0.01 mL then waiting 13.368342155590653 s
Aspirating 0.08675120174884797 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.1515323671884835 mL then waiting 27.554954756051302 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.095604479406029 mL then waiting 0 s
Aspirating 0.01 mL then waiting 6.319280611351132 s
Aspirating 0.0120980653911829 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.11770254479721189 mL then waiting 24.89320646971464 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.095604479406029 mL then waiting 0 s
Aspirating 0.01 mL then waiting 6.319280611351132 s
Aspirating 0.0120980653911829 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.11770254479721189 mL then waiting 24.89320646971464 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.095604479406029 mL then waiting 0 s
Aspirating 0.01 mL then waiting 6.319280611351132 s
Aspirating 0.0120980653911829 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.01 mL
Dispensing 0.11770254479721189 mL then waiting 24.89320646971464 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.01136343227699399 mL then waiting 0 s
Aspirating 0.02 mL then waiting 18.62130342051387 s
Aspirating 0.09116187421604992 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.12252530649304391 mL then waiting 9.713714607059956 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.01136343227699399 mL then waiting 0 s
Aspirating 0.02 mL then waiting 18.62130342051387 s
Aspirating 0.09116187421604992 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.12252530649304391 mL then waiting 9.713714607059956 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.01136343227699399 mL then waiting 0 s
Aspirating 0.02 mL then waiting 18.62130342051387 s
Aspirating 0.09116187421604992 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.12252530649304391 mL then waiting 9.713714607059956 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.03326820749789477 mL then waiting 0 s
Aspirating 0.02 mL then waiting 9.741480024531484 s
Aspirating 0.042036968376487495 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.09530517587438227 mL then waiting 17.687284676358104 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.03326820749789477 mL then waiting 0 s
Aspirating 0.02 mL then waiting 9.741480024531484 s
Aspirating 0.042036968376487495 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.09530517587438227 mL then waiting 17.687284676358104 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.03326820749789477 mL then waiting 0 s
Aspirating 0.02 mL then waiting 9.741480024531484 s
Aspirating 0.042036968376487495 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.09530517587438227 mL then waiting 17.687284676358104 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.0736371910199523 mL then waiting 0 s
Aspirating 0.02 mL then waiting 29.082126673310995 s
Aspirating 0.061026137322187424 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.15466332834213972 mL then waiting 1.9196648430079222 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.0736371910199523 mL then waiting 0 s
Aspirating 0.02 mL then waiting 29.082126673310995 s
Aspirating 0.061026137322187424 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.15466332834213972 mL then waiting 1.9196648430079222 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.0736371910199523 mL then waiting 0 s
Aspirating 0.02 mL then waiting 29.082126673310995 s
Aspirating 0.061026137322187424 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.15466332834213972 mL then waiting 1.9196648430079222 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.061055597569793466 mL then waiting 0 s
Aspirating 0.02 mL then waiting 8.133811969310045 s
Aspirating 0.0022374819964170456 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.08329307956621052 mL then waiting 9.17936621233821 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.061055597569793466 mL then waiting 0 s
Aspirating 0.02 mL then waiting 8.133811969310045 s
Aspirating 0.0022374819964170456 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.08329307956621052 mL then waiting 9.17936621233821 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.061055597569793466 mL then waiting 0 s
Aspirating 0.02 mL then waiting 8.133811969310045 s
Aspirating 0.0022374819964170456 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.08329307956621052 mL then waiting 9.17936621233821 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.04605272365733981 mL then waiting 0 s
Aspirating 0.02 mL then waiting 27.93589205481112 s
Aspirating 0.09457562668249012 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.16062835033982992 mL then waiting 23.5378741286695 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.04605272365733981 mL then waiting 0 s
Aspirating 0.02 mL then waiting 27.93589205481112 s
Aspirating 0.09457562668249012 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.16062835033982992 mL then waiting 23.5378741286695 s
Pipetting from vial liquid_source, amount: 0.02 mL
Aspirating 0.04605272365733981 mL then waiting 0 s
Aspirating 0.02 mL then waiting 27.93589205481112 s
Aspirating 0.09457562668249012 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.02 mL
Dispensing 0.16062835033982992 mL then waiting 23.5378741286695 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.024158623442053797 mL then waiting 0 s
Aspirating 0.05 mL then waiting 4.176948610693216 s
Aspirating 0.04409116124734283 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.11824978468939663 mL then waiting 1.5046070236712694 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.024158623442053797 mL then waiting 0 s
Aspirating 0.05 mL then waiting 4.176948610693216 s
Aspirating 0.04409116124734283 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.11824978468939663 mL then waiting 1.5046070236712694 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.024158623442053797 mL then waiting 0 s
Aspirating 0.05 mL then waiting 4.176948610693216 s
Aspirating 0.04409116124734283 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.11824978468939663 mL then waiting 1.5046070236712694 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.08298474475741387 mL then waiting 0 s
Aspirating 0.05 mL then waiting 16.017538094893098 s
Aspirating 0.0529187873005867 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1859035320580006 mL then waiting 16.21271942742169 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.08298474475741387 mL then waiting 0 s
Aspirating 0.05 mL then waiting 16.017538094893098 s
Aspirating 0.0529187873005867 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1859035320580006 mL then waiting 16.21271942742169 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.08298474475741387 mL then waiting 0 s
Aspirating 0.05 mL then waiting 16.017538094893098 s
Aspirating 0.0529187873005867 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1859035320580006 mL then waiting 16.21271942742169 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.0675580594688654 mL then waiting 0 s
Aspirating 0.05 mL then waiting 24.295298354700208 s
Aspirating 0.0279617864638567 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1455198459327221 mL then waiting 21.221702685579658 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.0675580594688654 mL then waiting 0 s
Aspirating 0.05 mL then waiting 24.295298354700208 s
Aspirating 0.0279617864638567 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1455198459327221 mL then waiting 21.221702685579658 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.0675580594688654 mL then waiting 0 s
Aspirating 0.05 mL then waiting 24.295298354700208 s
Aspirating 0.0279617864638567 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1455198459327221 mL then waiting 21.221702685579658 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.027091407775878908 mL then waiting 0 s
Aspirating 0.05 mL then waiting 11.76067454740405 s
Aspirating 0.0688267189078033 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1459181266836822 mL then waiting 6.046315496787429 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.027091407775878908 mL then waiting 0 s
Aspirating 0.05 mL then waiting 11.76067454740405 s
Aspirating 0.0688267189078033 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1459181266836822 mL then waiting 6.046315496787429 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.027091407775878908 mL then waiting 0 s
Aspirating 0.05 mL then waiting 11.76067454740405 s
Aspirating 0.0688267189078033 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.1459181266836822 mL then waiting 6.046315496787429 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.005235508736222983 mL then waiting 0 s
Aspirating 0.05 mL then waiting 19.876943053677678 s
Aspirating 0.019898648466914894 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.07513415720313787 mL then waiting 29.01396408677101 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.005235508736222983 mL then waiting 0 s
Aspirating 0.05 mL then waiting 19.876943053677678 s
Aspirating 0.019898648466914894 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.07513415720313787 mL then waiting 29.01396408677101 s
Pipetting from vial liquid_source, amount: 0.05 mL
Aspirating 0.005235508736222983 mL then waiting 0 s
Aspirating 0.05 mL then waiting 19.876943053677678 s
Aspirating 0.019898648466914894 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.05 mL
Dispensing 0.07513415720313787 mL then waiting 29.01396408677101 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.028958761971443894 mL then waiting 0 s
Aspirating 0.1 mL then waiting 26.706332713365555 s
Aspirating 0.06482507726177573 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19378383923321962 mL then waiting 17.921504639089108 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.028958761971443894 mL then waiting 0 s
Aspirating 0.1 mL then waiting 26.706332713365555 s
Aspirating 0.06482507726177573 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19378383923321962 mL then waiting 17.921504639089108 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.028958761971443894 mL then waiting 0 s
Aspirating 0.1 mL then waiting 26.706332713365555 s
Aspirating 0.06482507726177573 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19378383923321962 mL then waiting 17.921504639089108 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.06388256317004562 mL then waiting 0 s
Aspirating 0.1 mL then waiting 8.546751206740737 s
Aspirating 0.032160264998674394 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19604282816872 mL then waiting 3.5604772344231606 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.06388256317004562 mL then waiting 0 s
Aspirating 0.1 mL then waiting 8.546751206740737 s
Aspirating 0.032160264998674394 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19604282816872 mL then waiting 3.5604772344231606 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.06388256317004562 mL then waiting 0 s
Aspirating 0.1 mL then waiting 8.546751206740737 s
Aspirating 0.032160264998674394 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.19604282816872 mL then waiting 3.5604772344231606 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.0008299741894006729 mL then waiting 0 s
Aspirating 0.1 mL then waiting 5.406450172886252 s
Aspirating 0.015309544187039137 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.11613951837643982 mL then waiting 10.885404897853732 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.0008299741894006729 mL then waiting 0 s
Aspirating 0.1 mL then waiting 5.406450172886252 s
Aspirating 0.015309544187039137 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.11613951837643982 mL then waiting 10.885404897853732 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.0008299741894006729 mL then waiting 0 s
Aspirating 0.1 mL then waiting 5.406450172886252 s
Aspirating 0.015309544187039137 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.11613951837643982 mL then waiting 10.885404897853732 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.047897093743085865 mL then waiting 0 s
Aspirating 0.1 mL then waiting 12.406155494973063 s
Aspirating 0.09057093476876617 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.23846802851185203 mL then waiting 11.680859634652734 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.047897093743085865 mL then waiting 0 s
Aspirating 0.1 mL then waiting 12.406155494973063 s
Aspirating 0.09057093476876617 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.23846802851185203 mL then waiting 11.680859634652734 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.047897093743085865 mL then waiting 0 s
Aspirating 0.1 mL then waiting 12.406155494973063 s
Aspirating 0.09057093476876617 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.23846802851185203 mL then waiting 11.680859634652734 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.05750379227101803 mL then waiting 0 s
Aspirating 0.1 mL then waiting 22.833193726837635 s
Aspirating 0.006439013779163361 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.1639428060501814 mL then waiting 26.851899856701493 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.05750379227101803 mL then waiting 0 s
Aspirating 0.1 mL then waiting 22.833193726837635 s
Aspirating 0.006439013779163361 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.1639428060501814 mL then waiting 26.851899856701493 s
Pipetting from vial liquid_source, amount: 0.1 mL
Aspirating 0.05750379227101803 mL then waiting 0 s
Aspirating 0.1 mL then waiting 22.833193726837635 s
Aspirating 0.006439013779163361 mL then waiting 0 s
Pipetting into vial measurement_vial_0, amount: 0.1 mL
Dispensing 0.1639428060501814 mL then waiting 26.851899856701493 s
c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_base.py:94: RuntimeWarning: invalid value encountered in scalar divide
  std_measurement = np.std(measurements) / avg_measurement * 100  # % relative std
Traceback (most recent call last):
  File "c:\Users\Imaging Controller\Desktop\utoronto_demo\workflows\calibration_sdl_short.py", line 90, in <module>
    suggestions = recommender.get_suggestions(ax_client, volume, n=1)
  File "C:\Users\Imaging Controller\Desktop\utoronto_demo\../utoronto_demo\recommenders\pipeting_optimizer_honegumi.py", line 89, in get_suggestions
    params, trial_index = ax_client.get_next_trial(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\utils\common\executils.py", line 167, in actual_wrapper
    return func(*args, **kwargs)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\service\ax_client.py", line 543, in get_next_trial
    generator_run=self._gen_new_generator_run(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\service\ax_client.py", line 1781, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\generation_strategy.py", line 372, in gen
    return self._gen_multiple(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\generation_strategy.py", line 773, in _gen_multiple
    self._fit_current_model(data=data)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\generation_strategy.py", line 852, in _fit_current_model
    self._curr.fit(experiment=self.experiment, data=data)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\generation_node.py", line 237, in fit
    model_spec.fit(  # Stores the fitted model as `model_spec._fitted_model`
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\model_spec.py", line 147, in fit
    self._fitted_model = self.model_enum(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\registry.py", line 345, in __call__
    model_bridge = bridge_class(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\torch.py", line 132, in __init__
    super().__init__(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\base.py", line 213, in __init__
    self._fit_if_implemented(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\base.py", line 236, in _fit_if_implemented
    self._fit(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\modelbridge\torch.py", line 653, in _fit
    self.model.fit(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\models\torch\botorch_modular\model.py", line 338, in fit
    surrogate.fit(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py", line 567, in fit
    model = self._construct_model(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py", line 471, in _construct_model
    fit_botorch_model(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\ax\models\torch\botorch_modular\utils.py", line 301, in fit_botorch_model
    fit_gpytorch_mll(mll)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\fit.py", line 105, in fit_gpytorch_mll
    return FitGPyTorchMLL(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\utils\dispatcher.py", line 93, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\fit.py", line 205, in _fit_fallback
    result = optimizer(mll, closure=closure, **optimizer_kwargs)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\optim\fit.py", line 94, in fit_gpytorch_mll_scipy
    result = scipy_minimize(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\optim\core.py", line 110, in scipy_minimize
    raw = minimize_with_timeout(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\optim\utils\timeout.py", line 83, in minimize_with_timeout
    return optimize.minimize(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_minimize.py", line 731, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_lbfgsb_py.py", line 407, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 343, in fun_and_grad
    self._update_fun()
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 294, in _update_fun
    fx = self._wrapped_fun(self.x)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 20, in wrapped
    fx = fun(np.copy(x), *args)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_optimize.py", line 79, in __call__
    self._compute_if_needed(x, *args)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\scipy\optimize\_optimize.py", line 73, in _compute_if_needed
    fg = self.fun(x, *args)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\optim\closures\core.py", line 152, in __call__
    value_tensor, grad_tensors = self.closure(**kwargs)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\optim\closures\core.py", line 66, in __call__
    values = self.forward(**kwargs)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\botorch\optim\closures\model_closures.py", line 179, in closure
    log_likelihood = mll(
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\gpytorch\module.py", line 31, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\gpytorch\mlls\exact_marginal_log_likelihood.py", line 82, in forward
    res = output.log_prob(target)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\gpytorch\distributions\multivariate_normal.py", line 171, in log_prob
    return super().log_prob(value)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\torch\distributions\multivariate_normal.py", line 248, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\gpytorch\distributions\multivariate_normal.py", line 88, in _unbroadcasted_scale_tril
    ust = to_dense(self.lazy_covariance_matrix.cholesky())
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\linear_operator\operators\_linear_operator.py", line 1311, in cholesky
    chol = self._cholesky(upper=False)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\linear_operator\utils\memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\linear_operator\operators\_linear_operator.py", line 521, in _cholesky
    evaluated_mat = evaluated_kern_mat.to_dense()
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\linear_operator\utils\memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\linear_operator\operators\sum_linear_operator.py", line 81, in to_dense
    return (sum(linear_op.to_dense() for linear_op in self.linear_ops)).contiguous()
  File "C:\Users\Imaging Controller\anaconda3\envs\north_env\lib\site-packages\linear_operator\operators\sum_linear_operator.py", line 81, in <genexpr>
    return (sum(linear_op.to_dense() for linear_op in self.linear_ops)).contiguous()
KeyboardInterrupt
